Fix to use UTF-8 instead of US_ASCII
kittinunf/fuel pull request #816
Opened 2021-08-28 08:25 UTC by aytdm

## Description

Fix to use `Charsets.UTF-8` instead of `Charsets.US_ASCII`.
If there is no charset in the Content-Type header value, `Charsets.US_ASCII` is used and the multibyte character sets is garbled.
https://github.com/kittinunf/fuel/blob/823df71af8d9d70ed477d5d22eb0548045b95fad/fuel/src/main/kotlin/com/github/kittinunf/fuel/core/BodyRepresentation.kt#L29

I think it would be better to use `Charsets.UTF-8`. because the documentation says:
> https://fuel.gitbook.io/documentation/core/fuel#blocking-responses
> The default charset is UTF-8.

Fixes #815

## Type of change
Check all that apply

* [x]  Bug fix (a non-breaking change which fixes an issue)
* [ ]  New feature (a non-breaking change which adds functionality)
* [ ]  Breaking change (fix or feature that would cause existing functionality to not work as expected)
* [ ]  Refactoring (a change which changes the current internal or external interface)
* [ ]  This change requires a documentation update

## How Has This Been Tested?

I added a test case with multibyte character sets.

## Checklist:
* [x]  I have performed a self-review of my own code
* [ ]  I have commented my code, particularly in hard-to-understand areas
* [ ]  I have made corresponding changes to the documentation, if necessary
* [ ]  My changes generate no new compiler warnings
* [x]  I have added tests that prove my fix is effective or that my feature works
* [ ]  New and existing unit tests pass locally with my changes
* [ ]  Inspect the bytecode viewer, including reasoning why

2021-08-28 08:45 UTC, aytdm commented
I'm getting this error in Travis CI.

```bash
Could not authorize build request for...
```

Is there anything I should do on my side?

2021-08-29 02:08 UTC, SleeplessByte requested changes
The correct way to handle unset or incorrectly set character encoding is to use UTF-7, not 8.

2021-08-30 04:23 UTC, aytdm commented
Thank you for the detailed explanation to me. I understand now that it is not a bug.

Unfortunately, [UTF-7](https://datatracker.ietf.org/doc/html/rfc2152) is not supported by the JDK and cannot be specified. 
https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/nio/charset/Charset.html
So, the best I can do at this point is to remember to set the Content-Type header value with `charset=UTF-8`.
I hope RFC 6657 will be approved.

I'm going to close this PR for useless fixes. Thank you.

2021-08-30 04:23 UTC, closed without merging

2021-08-30 10:16 UTC, SleeplessByte commented
@aytdm You'll want `US-ASCII`. It's "equivalent" to the proposed UTF-7 (that didn't make it), but implemented before the UTF standard proliferated with a similar charset, but different positions.

But yes, setting `charset=UTF-8` is your best bet! :D

2021-08-30 12:16 UTC, aytdm commented
Thank you again :)